"""Password_reader

Revision ID: 8cbb450d194f
Revises: 7f5bea8c193f
Create Date: 2024-08-05 13:05:18.756000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cbb450d194f'
down_revision: Union[str, None] = '7f5bea8c193f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Flask_Table_Users', sa.Column('password', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Flask_Table_Users', 'password')
    # ### end Alembic commands ###
